title:
  de: Normal
  en: Default

options: options/default

tabs:
  tab_content:
    extends: migrate/tabs/content
    fields:
      text: false
      layouts: migrate/fields/base/layouts

    sidebar:
      sidebar_fields:
        type: fields
        fields:
          cover: migrate/fields/cover

  # Metadata
  tab_seo: tabs/seo
