title:
  de: Normal
  en: Default

options: options/default

tabs:
  # Content
  tab_content:
    extends: tabs/content
    fields:
      text: false
      layouts: fields/base/layouts

    sidebar:
      sidebar_fields:
        type: fields
        fields:
          cover: fields/cover

  # Files
  tab_files: tabs/files

  # Metadata
  tab_seo: tabs/seo
