title:
  de: Seite
  en: Site

tabs:
  # Index
  tab_index:
    label:
      de: Übersicht
      en: Overview
    icon: layers
    columns:
      full:
        sections:
          pages_main:
            extends: sections/base/posts
            headline:
              de: Hauptseiten
              en: Main pages
            sortBy: num asc
            templates:
              - news
              - about
              - assortment
              - lesetipps
              - calendar
              - grid-list
              - contact
            info: "{{ page.children.count }} Unterseite(n), {{ page.files.filterBy('extension', 'not in', ['webp', 'avif']).count }} Datei(en)"

          pages_rest:
            extends: sections/base/posts
            headline:
              de: Sonstige Seiten
              en: Miscellaneous
            sortBy: intendedTemplate desc title asc
            templates:
              - dependencies
              - feeds
              - default
            info: "Zuletzt bearbeitet am {{ page.modified('d.m.Y') }}"

          jobs:
            type: fields
            fields:
              headline_jobs:
                extends: fields/base/headline
                label:
                  de: Tätigkeiten
                  en: Various jobs

              archiveEvents:
                extends: fields/base/job
                label:
                  de: Veranstaltungen aussortieren
                  en: Generate metadata
                progress: Durchsuchen ..
                job: archiveEvents
                width: 1/4

              clearDejure:
                extends: fields/base/job
                label:
                  de: DJO-Cache leeren
                  en: Clear DJO cache
                progress: Leeren ..
                job: clearDejure
                width: 1/4

  # Lesetipps
  tab_lesetipps:
    extends: tabs/custom/lesetipps
    icon: book
    columns:
      left:
        sections:
          limit: false

      right:
        sections:
          posts_drafts:
            parent: site.find('lesetipps')

          posts_unlisted:
            parent: site.find('lesetipps')

      full:
        sections:
          posts_listed:
            parent: site.find('lesetipps')

  # News
  tab_news:
    extends: tabs/custom/news
    label:
      de: Aktuelles
      en: News
    columns:
      left:
        sections:
          limit: false

      right:
        sections:
          posts_drafts:
            parent: site.find('news')

          posts_unlisted:
            parent: site.find('news')

      full:
        sections:
          posts_listed:
            parent: site.find('news')

  # Settings
  tab_settings:
    extends: tabs/content
    label:
      de: Einstellungen
      en: Settings
    icon: settings
    fields:
      text: false

      shop:
        extends: fields/base/url
        label: Online-Shop
        required: true

      instagram:
        extends: fields/base/url
        label: Instagram

      awards:
        label:
          de: Auszeichnungen
          en: Awards
        type: structure
        columns:
          donor:
          award:
        fields:
          identifier:
            label: ID
            type: text
            width: 1/2

          award:
            label:
              de: Auszeichnung
              en: Award
            type: text
            width: 1/2

          donor:
            label:
              de: Stifter
              en: Donor
            type: text
            width: 1/2

          donorLink:
            label: Link
            type: url
            width: 1/2

          description:
            label:
              de: Beschreibung
              en: Description
            type: markdown

    sidebar:
      sidebar_fields:
        type: fields
        fields:
          mail:
            label: Mail
            type: email
            translate: false
            required: true

          phone:
            label:
              de: Telefon
              en: Phone
            type: tel
            translate: false
            required: true

          fax:
            label: Fax
            type: tel
            translate: false
            required: true

  # Default metadata
  tab_seo: tabs/seo
