title:
  de: Seite
  en: Site

files: false

tabs:
  # Dashboard
  dashboard:
    icon: dashboard
    columns:
      left:
        width: 2/3
        sections:
          lesetipps:
            extends: sections/articles
            headline:
              de: Lesetipps
              en: Recommendations
            parent: site.find("lesetipps")
            template: lesetipps.article
            create: lesetipps.article
            limit: 8
            image:
              query: page.getCover

      right:
        width: 1/3
        sections:
          news:
            extends: sections/articles
            headline: Aktuelles
            parent: site.find("news")
            create: news.article
            layout: list
            limit: 4

          events:
            extends: sections/articles
            headline: Veranstaltungen
            parent: site.find('kalender')
            template: calendar.event
            create: calendar.event
            layout: list
            subpages: false
            limit: 4
            empty: Keine Veranstaltungen!

          sort_out:
            type: fields
            fields:
              move_events:
                type: janitor
                label:
                  de: Veranstaltungen aussortieren
                  en: Generate metadata
                progress: Durchsuchen ..
                job: archiveEvents

          default_pages:
            headline:
              de: Seiten
              en: Pages
            type: pages
            create: default
            template:
              - about
              - assortment
              - grid-list
              - contact
            sortable: false

  settings:
    icon: settings
    preset: page
    pages: false

    fields:
      mail:
        label: Mail
        type: email
        width: 1/3

      shop:
        label:
          de: URL der Shopseite
          en: Shop URL
        type: url
        width: 2/3

      awards:
        label:
          de: Auszeichnungen
          en: Awards
        type: structure
        columns:
          award:
          donor:
          donorLink:
        fields:
          identifier:
            label:
              de: ID
              en: ID
            type: text
            width: 1/2

          award:
            label:
              de: Auszeichnung
              en: Award
            type: text
            width: 1/2

          donor:
            label:
              de: Stifter
              en: Donor
            type: text
            width: 1/2

          donorLink:
            label: Link
            type: url
            width: 1/2

          description:
            label:
              de: Beschreibung
              en: Description
            type: markdown

    sidebar:
      sidebar_files: false
      sidebar_pages:
        headline:
          de: Sonstige Seiten
          en: Other pages
        type: pages
        create: default
        template: default
        sortable: false

      sidebar_fields:
        type: fields
        fields:
          fallback:
            extends: fields/single-cover
            label:
              de: Reservebild
              en: Fallback image
            query: site.images
            image:
              ratio: 3/4
